drop table T_USER;
drop table T_ROLE;
drop table T_USER_ROLE;
drop table T_MANUFACTURER;
drop table T_SDK;
drop table T_PRODUCT;
drop table T_CORPORATION;
drop table T_CHANNEL;
drop table T_PRODUCT_RELATIVE;
create table T_ROLE
( 
roleId integer  GENERATED BY DEFAULT AS IDENTITY primary key, 
roleName varchar(100)  
);
create table T_USER( 
userName varchar(100) primary key, 
fullName varchar(100) , 
password varchar(100) );

create table T_USER_ROLE(  
userName varchar(100), 
roleId integer  );
create table T_RIGHT(opId varchar(100) primary key,
parentId varchar(100),name varchar(200), 
actionNo integer, 
type integer );

create table T_ROLE_RIGHT(  
roleId integer, 
opId  varchar(100)  
);

create table T_MANUFACTURER(
id integer not null generated always as identity(start with 1,increment by 1) primary key,
name varchar(50),
description varchar(200),
edit_time timestamp);

create table T_SDK(
id integer not null generated always as identity(start with 1,increment by 1) primary key,
m_id integer,
name varchar(50),
version varchar(20),
description varchar(200),
file_relative_path varchar(200),
file_upload_time timestamp);


create table T_CORPORATION(
id integer not null generated always as identity(start with 1,increment by 1) primary key,
name varchar(50),
description varchar(200),
edit_time timestamp);

create table T_Channel(
id integer not null generated always as identity(start with 1,increment by 1) primary key,
name varchar(50),
userName varchar(100), 
description varchar(200),
edit_time timestamp);

create table T_PRODUCT(
id integer not null generated always as identity(start with 1,increment by 1) primary key,
corporation_id integer,
version varchar(50),
name varchar(50),
description varchar(200),
APP_KEY varchar(50),
APP_CHANNEL varchar(50),
file_relative_path varchar(200),
file_upload_time timestamp);

create table T_PRODUCT_RELATIVE(
id integer not null generated always as identity(start with 1,increment by 1) primary key,
product_id integer,
channel_id integer,
sdk_id integer,
rate NUMERIC(4,2),
name varchar(50),
description varchar(200),
file_relative_path varchar(200),
file_upload_time timestamp);

create table CUSTOMER_INFO  (
IMEI                 VARCHAR(15),
MODEL                VARCHAR(16),
LOGIN_IP             VARCHAR(16),
CUSTOMER_ID          VARCHAR(64) ,
PRODUCT               VARCHAR(16),--对应产品表的name
--APP_NAME            VARCHAR(32) ,
--APP_VERSION          VARCHAR(16),
ANDROID_VERSION      VARCHAR(16),
ACTIVE_TIME          timestamp);

create table CUSTOMER_LOGIN_LOG_INFO  (
IMEI                 VARCHAR(15),
LOGIN_IP             VARCHAR(16),
CUSTOMER_ID              VARCHAR(64),
PRODUCT               VARCHAR(16),--对应产品表的name
--APP_NAME            VARCHAR(32),
--APP_VERSION          VARCHAR(16),
LOGIN_TIME			timestamp,
LOGOUT_TIME         timestamp,
ONLINE_TIME          VARCHAR(16));

drop table SDK_FEE_DETAIL ;
create table SDK_FEE_DETAIL  (
ORDER_ID             VARCHAR(32) ,
PRICE                INTEGER ,
STATUS               INTEGER ,
OPERATOR             CHAR(1),
SIGNER               VARCHAR(64),
APP_KEY              VARCHAR(32) ,
PRODUCT               VARCHAR(16),--产品
SDK_PARAM            VARCHAR(16),
SYNC_TIME            timestamp
);


create table LOCAL_FEE_DETAIL  (
IMEI                 VARCHAR(15),
LOGIN_IP             VARCHAR(16),
CUSTOMER_ID              VARCHAR(64) ,
PRODUCT               VARCHAR(16),
FEE_NODE             CHAR(1),
PRICE                INTEGER ,
STATUS               INTEGER ,
FEE_TIME             date);

create table SDK_FEE_STA  (
SUCCESS_FEE       INTEGER,
FAILED_FEE        INTEGER,
SUCCESS_COUNT INTEGER,
FAILED_COUNT INTEGER,
PRODUCT               VARCHAR(16),--产品
sta_date            VARCHAR(8));

create table LOCAL_FEE_STA  (
SUCCESS_FEE       INTEGER,
FAILED_FEE        INTEGER,
SUCCESS_COUNT INTEGER,
FAILED_COUNT INTEGER,
PRODUCT               VARCHAR(16),--产品
FEE_NODE             CHAR(1),
sta_date            VARCHAR(8) );
--
create table ACTIVE_STA
(
ONLINE_CUSTOMER_COUNT INTEGER,
NEW_CUSTOMER_COUNT INTEGER,
PRODUCT  VARCHAR(16),
STA_DATE VARCHAR(8)
);
drop table SDK_TRANSFER_STA;
CREATE TABLE SDK_TRANSFER_STA
(
PRODUCT VARCHAR(16),
LOCAL_SUCCESS_FEE INTEGER,
SDK_SUCCESS_FEE INTEGER,
STA_DATE VARCHAR(8)
);


